# Default values for labs-helmchart-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Note the commented properties have a default value by environment if specify a value here, it set up this value for all environments
environment: "dev"

replicaCount: 1

metadata:
  namePrefix: "labs-soft"
  name: "gke-deploy"
  defaultNamespace: "labs-dev"

image:
  repository: luigisamurai/gkedeploy
  tag: "testlabsdeploy004"
  pullPolicy: Always

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

splunk:
  repository: splunk/universalforwarder
  tag: 9.3.3
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "400m"
      memory: "256Mi"
    limits:
      cpu: 1
      memory: "512Mi"

service:
  type: ClusterIP
  port: 80
  targetPort: 9081

livenessProbe:
  path: /actuator/health/liveness
  port: 9081
  initialDelaySeconds: 60
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  path: /actuator/health/readiness
  port: 9081
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1

envs:
  kafkaBootstrapServers: "broker2:9092"
  redisHost: "redis"
  splunkStartArgs: "--accept-license --answer-yes"
  splunkGroup: "root"
  splunkPort: "8089"
  splunkServer: "lpec5009spkdm01.cardinalhealth.net"
  splunkUser: "root"
  splunkCmd: "add monitor /var/log -index ecomm_nxtgen_non-prod"
  sslBundleRedis: "/etc/secrets/redis-cacert.pem"

nodeSelector: {}

tolerations: []

affinity: {}

securityContext: { }

podSecurityContext: { }

gcp:
  serviceAccount: "gke-sa"
  projectNumber: "230862495170"
  secretManager:
    envsVars:
      secretProvider: "gcp"
      secretSyncEnabled: false
      secrets:
        - name: "env-vars-dev" 
          fileName: "secrets.env"
          key: ""
          envVar: ""
        - name: "cache-ssl-pem"
          fileName: "redis-cacert.pem"
          key: ""
          envVar: ""
    splunk:
      secretProvider: "gcp"
      secretSyncEnabled: false
      secrets:
        - name: "splunk-dev"
          fileName: "splunk.env"
          key: ""
          envVar: ""
