server:
  port: 9081
spring:
  application:
    name: LABS_GKE_DEPLOY
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    streams:
      application-id: ${spring.application.name}
    admin:
      auto-create: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

management:
  endpoint:
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: ping,redis,kafkaHealthCheck
        liveness:
          include: ping
  endpoints:
    web.exposure.include: health,info


health:
  kafka:
    rebalancing-max: PT1M