server:
  port: 9081
spring:
  application:
    name: LABS_GKE_DEPLOY
  kafka:
    enabled: false
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    streams:
      auto-startup: ${spring.kafka.enabled}
      application-id: ${spring.application.name}
    admin:
      auto-create: true
  data:
    ssl:
      enabled: true
      bundle: redisSslBundle
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  ssl:
    bundle:
      pem:
        redisSslBundle:
          truststore:
            certificate: ${ssl_bundle_redis}

management:
  health:
    redis:
      enabled: false # Disable to test with redis
  endpoint:
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: ping #,redis,kafkaHealthCheck
        liveness:
          include: ping
  endpoints:
    web.exposure.include: health,info


health:
  kafka:
    rebalancing-max: PT1M