server:
  port: 9081
spring:
  application:
    name: LABS_GKE_DEPLOY
  jmx:
    enabled: true
  kafka:
    enabled: false
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    streams:
      auto-startup: ${spring.kafka.enabled}
      application-id: ${spring.application.name}
      properties:
        rocksdb.config.setter: com.labs.repartitioner.metrics.CustomRocksDBConfigSetter
    admin:
      auto-create: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

management:
  health:
    redis:
      enabled: false # Disable to test with redis
  endpoint:
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: ping #,redis,kafkaHealthCheck
        liveness:
          include: ping
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${ENVIRONMENT:local}
      host: ${HOSTNAME:localhost}


health:
  kafka:
    rebalancing-max: PT1M

logging:
  file:
    name: ${logging_file_name:logs/app.log}