server:
  port: 9081
spring:
  application:
    name: Repartitioner
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    streams:
      application-id: ${spring.application.name}
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

management:
  info:
    build.enable: false
    git.enabled: true
    env.enabled: true
  health:
    binders.enabled: true
    diskSpace.enabled: false
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
