apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  server.properties: |
    process.roles=broker,controller
    node.id={{ .Values.broker.id }}
    controller.quorum.voters={{ .Values.broker.id }}@{{ .Values.broker.name }}:{{ .Values.broker.controllerPort }}
    listeners=PLAINTEXT://:{{ .Values.broker.clientPort }},CONTROLLER://:{{ .Values.broker.controllerPort }}
    inter.broker.listener.name=PLAINTEXT
    advertised.listeners=PLAINTEXT://{{ .Values.broker.advertisedHost }}:{{ .Values.broker.clientPort }}
    controller.listener.names=CONTROLLER
    listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
    num.network.threads=3
    num.io.threads=8
    socket.send.buffer.bytes=102400
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    log.dirs=/tmp/kraft-combined-logs
    num.partitions=1
    num.recovery.threads.per.data.dir=1
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    log.retention.hours=168
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000