# clustersecretstore.yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: safari-gke-462517
      auth:
        workloadIdentity:
          clusterLocation: us-east1-b
          clusterName: labs-kube
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
