apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "labs-helmchart-base.buildName" (list . "deploy") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labs-helmchart-base.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "labs-helmchart-base.selector-labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labs-helmchart-base.selector-labels" . | nindent 8 }}
    spec:
      {{- if not (empty .Values.gcp.serviceAccount) }}
      serviceAccountName: {{ .Values.gcp.serviceAccount }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ .Values.metadata.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}

          envFrom:
            - configMapRef:
                name: {{ include "labs-helmchart-base.buildName" (list . "envcfg") }}
          
          {{- if not .Values.gcp.secretSync.enabled }}
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:file:/etc/secrets/secrets.env"
          {{- else }}   
          env:
           {{- range $secret := .Values.gcp.secretSync.secrets }}
            - name: {{ $secret.key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "labs-helmchart-base.buildName" (list $ "sec") }}
                  key: {{ $secret.key }}
            {{- end }}
          {{- end }}   

          volumeMounts:
            - name: env-vars-volume
              mountPath: "/etc/secrets"
              readOnly: true

          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}

          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}

      volumes:
        {{- if eq .Values.gcp.secretProvider "gcp" }}
        - name: env-vars-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "labs-helmchart-base.buildName" (list . "envsp") }}
        {{- else if eq .Values.gcp.secretProvider "gke" }}
        - name: env-vars-volume
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "labs-helmchart-base.buildName" (list . "envsp") }}
        {{- else }}
        - name: env-vars-volume
          secret:
            secretName: {{ include "labs-helmchart-base.buildName" (list . "envfile") }}
            defaultMode: 0640
            items:
              - key: secrets.env
                path: secrets.env
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
