{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name:  {{ include "labs-helmchart-base.buildName" (list . "extSec") }}
  labels:
    {{- include "labs-helmchart-base.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName | quote }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.keda.secretName | quote }}
    creationPolicy: Owner
  data:
    - secretKey: sasl_username
      remoteRef:
        key: {{ .Values.externalSecret.secretManagerName | quote }}
        property: username
    - secretKey: sasl_password
      remoteRef:
        key: {{ .Values.externalSecret.secretManagerName | quote }}
        property: password
{{- end }}
