{{- if (and .Values.keda.secretEnabled (not .Values.externalSecret.enabled)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keda.secretName | quote }}
  labels:
    {{- include "labs-helmchart-base.labels" . | nindent 4 }}
type: Opaque
data:
  sasl_username: VFVfQVBJX0tFWQ==
  sasl_password: VFVfQVBJX1NFQ1JFVA==
  tls_enabled: ZW5hYmxl
{{- end }}
