{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "labs-helmchart-base.buildName" (list . "scale") }}
  labels:
    {{- include "labs-helmchart-base.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "labs-helmchart-base.buildName" (list . "dep") }}

  minReplicaCount: {{ .Values.keda.minReplicas }}
  maxReplicaCount: {{ .Values.replicaCount }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: {{ .Values.keda.stabilizationWindowSeconds }}

  triggers:
    - type: kafka
      metadata:
        {{- toYaml .Values.keda.trigger | nindent 6 }}
      authenticationRef:
        name: {{ include "labs-helmchart-base.buildName" (list . "tauth") }}
{{- end }}
