apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "labs-helmchart-base.buildName" (list . "envsp") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labs-helmchart-base.labels" . | nindent 4 }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: {{ .Values.secretManager.envsVars }}
        path: secrets.env
