{{- $sa := lookup "v1" "ServiceAccount" .Release.Namespace .Values.serviceAccount.name }}
{{- if not $sa }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.name }}@{{ .Values.serviceAccount.project }}.iam.gserviceaccount.com
{{- end }}