apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "cah-helmchart-base.buildName" (list . "spksp") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cah-helmchart-base.labels" . | nindent 4 }}
      {{- include "cah-helmchart-base.workload-labels" . | nindent 4 }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: {{ .Values.secretManager.splunk }}
        path: splunk.env
  secretObjects:
    - secretName: {{ include "cah-helmchart-base.buildName" (list . "secsplunk") }}
      type: Opaque
      data:
        - key: SPLUNK_PASSWORD
          objectName: SPLUNK_PASSWORD
