{{- if .Values.splunk.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "labs-helmchart-base.buildName" (list . "spkcfg") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labs-helmchart-base.labels" . | nindent 4 }}
    {{- include "labs-helmchart-base.workload-labels" . | nindent 4 }}
data:
  "SPLUNK_START_ARGS": "--accept-license"
  "SPLUNK_FORWARD_SERVER": {{ .Values.splunk.env.server | quote }}
  "SPLUNK_ADD": "monitor {{ .Values.splunk.mountPath }}/{{ .Values.splunk.logFile }} -sourcetype {{ .Values.splunk.env.sourcetype }} -index {{ .Values.splunk.env.index }}"
  "SPLUNK_GROUP": "root"
{{- end }}
