{{- if .Values.splunk.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "labs-helmchart-base.buildName" (list . "spkcfg") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labs-helmchart-base.labels" . | nindent 4 }}
    {{- include "labs-helmchart-base.workload-labels" . | nindent 4 }}
data:
  "SPLUNK_GROUP": {{ .Values.splunk.env.group | quote }}
  "SPLUNK_FORWARD_SERVER": {{ .Values.splunk.env.server | quote }}
  "SPLUNK_CMD": "add monitor {{ .Values.envs.loggingFileName }} -sourcetype {{ .Values.metadata.name }} -index {{ .Values.splunk.env.index }}"
{{- end }}
