name: CI & Publish

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  workflow_dispatch: {}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle 8.9
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9

      - name: Build and Test with Coverage
        run: |
          gradle --version
          gradle test jacocoTestReport

  publish:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event_name == 'push'

    permissions:
      contents: read

    # Si usas Environments protegidos, descomenta:
    # environment: release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta (tags & labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/gkedeploy
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            # 'latest' solo en la default branch (main)
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          no-cache: true
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
