name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

# Evita ejecuciones viejas si llegan más commits al mismo PR
concurrency:
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle 8.9
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9

      - name: Build and Test with Coverage
        run: |
          gradle --version
          gradle test jacocoTestReport

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Checking Greeting Stream coverage
        run: |
          COVERAGE=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@covered)" build/reports/jacoco/test/jacocoTestReport.xml)
          MISSED=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@missed)" build/reports/jacoco/test/jacocoTestReport.xml)
          TOTAL=$((COVERAGE + MISSED))
          PERCENTAGE=$((100 * COVERAGE / TOTAL))
          echo "Coverage is $PERCENTAGE%"
          if [ "$PERCENTAGE" -lt 80 ]; then
            echo "Coverage is below 80% ($PERCENTAGE%)"
            exit 1
          fi
